<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ProvidersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvidersRepository extends EntityRepository
{
    /**
     * @param $listData
     * @param $age
     * @return array
     */
    public function prepareViewData($listData, $age)
    {
        $resultArray = [];
        if(count($listData) > 0)
        {
            foreach ($listData as $result) {
                $itemArray = [
                    'name' => $result->getName(),
                    'basePrice' => $result->getBasePrice(),
                    'minAge' => $result->getMinAge(),
                    'maxAge' => $result->getMaxAge(),
                    'enable' => ($age <= $result->getMaxAge() && $age >= $result->getMinAge()) ? 'true' : 'false',
                    'premium' => $this->calculatePremium($result->getBasePrice(), $age)
                ];
                array_push($resultArray, $itemArray);
            }
        }

        return $resultArray;
    }

    /**
     * @param $dob
     * @return int
     */
    public function getAge($dob){
        $age = 0;
        if($dob) {
            $age = date_diff(date_create($dob), date_create('today'))->y;
        }

        return $age;
    }

    /**
     * @param $basePrice
     * @param $age
     * @return float|int
     */
    public function calculatePremium($basePrice, $age)
    {
        $percentage = 0;
        $premiumAmount = 0;
        if($basePrice && $age){
            if ($age >= 18 && $age < 26) {
                $percentage = 2.30;
            }else if($age >= 26 && $age < 31){
                $percentage = 1.20;
            }else if($age >= 31 && $age < 61){
                $percentage = 3.50;
            }else if($age >= 61){
                $percentage = 4;
            }

            $percAmount = ($basePrice * $percentage) / 100;
            $premiumAmount = $basePrice + $percAmount;

        }

        return $premiumAmount;


    }
}
